name: Deploy to AWS
on:
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            set -e
            mkdir -p ~/my-docker-flask
            cat > ~/my-docker-flask/docker-compose.prod.yml <<'EOF'
services:
  web:
    image: YOUR_DOCKERHUB_USER/my-docker-flask:latest
    ports:
      - "5000:5000"
EOF
            docker compose -f ~/my-docker-flask/docker-compose.prod.yml pull
            docker compose -f ~/my-docker-flask/docker-compose.prod.yml up -d
            docker ps
